### ISSUE TITLE
Mozilla Firefox 嚴重緩慢

### ISSUE THREAD

**Issue by Vdragon** [g0v/g0village-8bit#11]
如題，目前的版本大部份時間是完全卡住的，有時候只能直接 kill 掉 process
Firefox release channel
Ubuntu 13.04 x86 32bit
NVIDIA GeForce GTS250 using official driver 304.88

**Comment by racklin** [comment]
@Vdragon 可以試試新的無特效版本，我實測 CPU 由 75% -> 25%

**Comment by racklin** [comment]
經測試， Mac Firefox 22 以上OK, Ubuntu / Debian Linux 尚有問題。
