### ISSUE TITLE
村長很渴

### ISSUE THREAD

**Issue by caasi** [g0v/g0village-8bit#16]
與高村長戰鬥多次後，遇到高村長一直行動，不斷喝飲料，不繼續戰鬥。

![drink0](https://f.cloud.github.com/assets/1164470/965054/141a025e-0523-11e3-9766-55ac759813c3.png)
![drink2](https://f.cloud.github.com/assets/1164470/965055/1489515e-0523-11e3-9c94-c3441ccc6eea.png)
![drinkn](https://f.cloud.github.com/assets/1164470/965056/14906e30-0523-11e3-8bea-d6dd6202e6d4.png)

**Comment by racklin** [comment]
光看到 2784 一路喝到 33084 我狂笑不已，完全無法修正這個 bug.

**Comment by jimyhuang** [comment]
（其實是完全不想修？）
