### ISSUE TITLE
clkao v.s. 高村長

### ISSUE THREAD

**Issue by bcbcarl** [g0v/g0village-8bit#20]
請問一下 clkao 和高村長是甚麼關係？
這個算是 feature 還是 bug？

![(screenshot)](http://i.imgur.com/EmycTgt.png)

**Comment by bcbcarl** [comment]
經過數次測試，我覺得這應該是 feature，有人可以確認一下嗎？

**Comment by audreyt** [comment]
這個是 feature (所以出場對話是「疑～」)。

在遊戲裡，clkao 和高村長的關係大致等同於＜七龍珠＞裡的神和比克的關係？
