### ISSUE TITLE
火狐 23.0.1 無背景

### ISSUE THREAD

**Issue by caasi** [g0v/g0village-8bit#28]
目前已知受災戶： @jbytw @ipaaa

圖片來源： @jbytw 

![hd0bghg](https://f.cloud.github.com/assets/1164470/1013820/f924cf3c-0b9a-11e3-84e5-cdb4f8037161.png)

**Comment by racklin** [comment]
應該是網路太慢，尚未載入完全部的 assets 便進入遊戲的 bugs, 已修正。
