### ISSUE TITLE
說明「高挫折」

### ISSUE THREAD

**Issue by kcwu** [g0v/g0village-8bit#29]
一般人不知道「高挫折」的由來

不知道能不能 hover 在「高挫折」時出現解釋, 或是點下去連到新聞網頁

**Comment by Superbil** [comment]
也可以引導到 g0v 黑話，順便可以看看其他黑話語錄
https://g0v.hackpad.com/g0v--MI7fGNIdygb

**Comment by racklin** [comment]
已加入了。
