### ISSUE TITLE
Firefox 有點慢

### ISSUE THREAD

**Issue by kanru** [g0v/g0village-8bit#4]
Profiling 的結果
![2013-08-10-095509_924x522_scrot](https://f.cloud.github.com/assets/17571/941935/78bc979c-0160-11e3-82b5-476ade0cdba4.png)

**Comment by caasi** [comment]
我的 FireFox 直接停住不會動XD

**Comment by Vdragon** [comment]
停住不會動+1
只好發動 SIGKILL
Ubuntu 13.04 x86-32bit
