### ISSUE TITLE
Google Chrome 中從其他分頁切換回遊戲分頁耗時過久

### ISSUE THREAD

**Issue by Vdragon** [g0v/g0village-8bit#7]
經粗估切換所需時間約 17 秒
建議想個方法減少等待分頁回應時間
![20130810_009](https://f.cloud.github.com/assets/1192163/942766/b9e736a6-01d2-11e3-8794-04a4a36290a9.jpg)
#### 發生問題的環境

Ubuntu 13.04 x86 32位元版本
來自 PPA:Kubuntu/backports 的K桌面環境(KDE)
Google Chrome 版本：28.0.1500.95
intel i7 3Ghz
NVIDIA GeForce GTS 250

**Comment by audreyt** [comment]
加上 Debounce 了，請 shift-refresh 再測一次看看，如果仍有一樣的狀況再重啟 issue，感謝！

**Comment by Vdragon** [comment]
耗時問題已無法再實現 :D
